export const API_CONFIG = {
  BASE_URL: 'https://www.alphavantage.co/query',
  API_KEY: '0GLLN7BBVWUV26FY',
  FUNCTIONS: {
    TIME_SERIES_INTRADAY: 'TIME_SERIES_INTRADAY',
    TIME_SERIES_DAILY: 'TIME_SERIES_DAILY',
    TIME_SERIES_DAILY_ADJUSTED: 'TIME_SERIES_DAILY_ADJUSTED',
    TIME_SERIES_WEEKLY: 'TIME_SERIES_WEEKLY',
    TIME_SERIES_WEEKLY_ADJUSTED: 'TIME_SERIES_WEEKLY_ADJUSTED',
    TIME_SERIES_MONTHLY: 'TIME_SERIES_MONTHLY',
    TIME_SERIES_MONTHLY_ADJUSTED: 'TIME_SERIES_MONTHLY_ADJUSTED',
    GLOBAL_QUOTE: 'GLOBAL_QUOTE',
    SYMBOL_SEARCH: 'SYMBOL_SEARCH',
    MARKET_STATUS: 'MARKET_STATUS',
    
    TOP_GAINERS_LOSERS: 'TOP_GAINERS_LOSERS',
    NEWS_SENTIMENT: 'NEWS_SENTIMENT',
    
    OVERVIEW: 'OVERVIEW',
    EARNINGS: 'EARNINGS',
    INCOME_STATEMENT: 'INCOME_STATEMENT',
    BALANCE_SHEET: 'BALANCE_SHEET',
    CASH_FLOW: 'CASH_FLOW',
    
    SMA: 'SMA',
    EMA: 'EMA',
    RSI: 'RSI',
    MACD: 'MACD',
    BBANDS: 'BBANDS',
    STOCH: 'STOCH',
  },
};

export const CACHE_CONFIG = {
  EXPIRATION_TIME: 5 * 60 * 1000,
  KEYS: {
    TOP_GAINERS_LOSERS: 'topGainersLosers',
    WATCHLISTS: 'watchlists',
    STOCK_DETAILS: 'stockDetails',
    THEME: 'theme',
  },
};
export const lightTheme = {
  mode: 'light',
  colors: {
    primary: '#007AFF',
    secondary: '#5856D6',
    background: '#FFFFFF',
    surface: '#F2F2F7',
    card: '#FFFFFF',
    text: '#000000',
    textSecondary: '#8E8E93',
    border: '#E5E5EA',
    success: '#34C759',
    error: '#FF3B30',
    warning: '#FF9500',
    accent: '#FF2D92',
    positive: '#30D158',
    negative: '#FF453A',
    neutral: '#8E8E93',
    tabBarBackground: '#F2F2F7',
    tabBarInactive: '#8E8E93',
    modalBackground: 'rgba(0,0,0,0.5)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 24,
    xxl: 32,
  },
};

export const darkTheme = {
  mode: 'dark',
  colors: {
    primary: '#0A84FF',
    secondary: '#5E5CE6',
    background: '#000000',
    surface: '#1C1C1E',
    card: '#2C2C2E',
    text: '#FFFFFF',
    textSecondary: '#8E8E93',
    border: '#38383A',
    success: '#30D158',
    error: '#FF453A',
    warning: '#FF9F0A',
    accent: '#FF2D92',
    positive: '#30D158',
    negative: '#FF453A',
    neutral: '#8E8E93',
    tabBarBackground: '#1C1C1E',
    tabBarInactive: '#8E8E93',
    modalBackground: 'rgba(0,0,0,0.8)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 24,
    xxl: 32,
  },
}; 